### PR TITLE
Update Import of QWidget to qt5

### PR DESCRIPTION
**Pull request by lorenz-halt**
python demo is working on kinetic, cpp is compiling but crashing when loaded.

### CODE REVIEW

**Comment by lucasw** [comment]
I imagine there needs to be cmake logic to detect versions like in https://github.com/lucasw/rviz_camera_stream/commit/9f34fca79365b9e37fb156c2ce170d581ce20a58 , or a separate `kinetic-devel` branch.

Same for the python, it needs a kinetic branch or a way to import qt5 if it is available, otherwise qt4.

I'll be able to take a closer look at this a week from now.

**Comment by lucasw** [comment]
Tried this on jade and it works, don't need conditional imports for qt4 vs. qt5.

**Comment by lorenz-halt** [comment]
Sorry for the delay... Actually I tested it on indigo as well and no problems there.

**Comment by lucasw** [comment]
#4 says it doesn't work on their jade, why does it work on mine?

**Pull request merged**
